added week7 large margin intuition
mehrdad-dev/ml-andrew-ng-code pull request #11
Opened 2020-10-24 07:09 UTC by nargesrzn

2020-10-24 18:23 UTC, mehrdad-dev requested changes
read comments

2020-10-24 18:23 UTC, mehrdad-dev commented on content/week7/large-margin-intuition.md
> +یک راه مفید برای فکر کردن راجع به ماشین های بردار پشتیبان این است که آن ها را یک طبقه بندی کننده با حاشیه اطمینان زیاد تصور کنیم.
آنها را به عنوان طبقه بندی کننده های حاشیه بزرگ در نظر بگیرید

2020-10-24 18:23 UTC, mehrdad-dev commented on content/week7/large-margin-intuition.md
> +مرز تصمیم گیری را از رگریسیون لجستیک به یاد آوردید (خطی که نمونه های مثبت و منفی را از هم جدا می کرد). خصوصیت ویژه ای که مرز تصمیم گیری در SVMها دارد این است که تا جای ممکن، از نمونه های مثبت و منفی
ترجمه svm و بنویس لطفا

2020-10-24 18:23 UTC, mehrdad-dev commented on content/week7/large-margin-intuition.md
> +فاصله مرز تصمیم گیری از نزدیک ترین نمونه، حاشیه اطمینان نامیده می شود. از آن جایی که SVMها این حاشیه را حداکثر می کنند، اغلب به آن ها طبقه بندی کننده با حاشیه اطمینان زیاد می گویند.
فاصله مرز تصمیم گیری تا نزدیک ترین نمونه
 نه از

2020-10-25 07:12 UTC, nargesrzn commented on content/week7/large-margin-intuition.md
> +title: "درک حاشیه اطمینان زیاد"
منظور از حاشیه در واقع فاصله ای است که داده از خط جداکننده داره، به نظرم اومد که "زیاد" صفت مناسب تری باشه

![svm](https://user-images.githubusercontent.com/59249853/97100998-caf35f80-16ae-11eb-845c-34f804a46a33.png)

2020-10-25 07:19 UTC, nargesrzn commented on content/week7/large-margin-intuition.md
> +یک راه مفید برای فکر کردن راجع به ماشین های بردار پشتیبان این است که آن ها را یک طبقه بندی کننده با حاشیه اطمینان زیاد تصور کنیم.
تو این قسمت منظورش اینه که طوری طبقه بندی می کنه داده ها رو که حاشیه اطمینان خوبی دارن یعنی اینکه خطی رو انتخاب می کنیم برای جداسازی داده ها که تا جای ممکن از نزدیکترین داده ها به اون خط فاصله دارن که اگر داده یه کم کمتر یا زیادتر باشه بازم درست طبقه بندی بشه یعنی اینطوری نشه که مثلا اگه یه داده جدیدی داریم که یه کمی به کلاس اشتباه نزدیکه، بیوفته تو اون کلاس اشتباه. یعنی با حاشیه اطمینان خوبی درست طبقه بندی بشه

2020-10-25 07:27 UTC, nargesrzn commented on content/week7/large-margin-intuition.md
> +مرز تصمیم گیری را از رگریسیون لجستیک به یاد آوردید (خطی که نمونه های مثبت و منفی را از هم جدا می کرد). خصوصیت ویژه ای که مرز تصمیم گیری در SVMها دارد این است که تا جای ممکن، از نمونه های مثبت و منفی
چون تو قسمت قبلی نوشته شده بود که مخفف چیه منم دیگه تکرارش نکردم ولی اگه فکر می کنی لازمه، بنویسم

![optimization](https://user-images.githubusercontent.com/59249853/97101217-c62fab00-16b0-11eb-936c-ce272770cfc1.png)

2020-10-25 08:39 UTC, mehrdad-dev commented on content/week7/large-margin-intuition.md
> +یک راه مفید برای فکر کردن راجع به ماشین های بردار پشتیبان این است که آن ها را یک طبقه بندی کننده با حاشیه اطمینان زیاد تصور کنیم.
میدونم منظورش چیه
طبق جمله ای که خودش نوشته اونطوری بهش نزدیک تره که بازم همون منظور رو میرسونه
فقط باید یک تغییری بدیم:
آنها را به عنوان طبقه بندی کننده هایی که حاشیه اطمینان زیادی دارند در نظر بگیرید

2020-10-25 08:40 UTC, mehrdad-dev commented on content/week7/large-margin-intuition.md
> +مرز تصمیم گیری را از رگریسیون لجستیک به یاد آوردید (خطی که نمونه های مثبت و منفی را از هم جدا می کرد). خصوصیت ویژه ای که مرز تصمیم گیری در SVMها دارد این است که تا جای ممکن، از نمونه های مثبت و منفی
اره اینارو قراره مث هفته اول کنم
یعنی فارسیش باشه بعد روش نگه داری انگلیسیش بیاد
اینجوری دوباره کاری میشه بخوایم پاک کنیم درست کنیم

2020-10-25 08:45 UTC, mehrdad-dev commented on content/week7/large-margin-intuition.md
> +title: "درک حاشیه اطمینان زیاد"
خوبه منطقیه

2020-10-25 13:47 UTC, mehrdad-dev reviewed
Thanks ❤️

2020-10-25 13:47 UTC, merged