week9 start
mehrdad-dev/ml-andrew-ng-code pull request #13
Opened 2020-10-28 21:05 UTC by faribajpr

2020-10-29 14:30 UTC, mehrdad-dev requested changes

2020-10-29 14:30 UTC, mehrdad-dev commented on content/week9/developing-evaluating-anomaly-detection-system.md
> +برای ارزیابی الگوریتم یادگیری، داده‌های دارای برچسب را به نمونه‌های ناهنجار و غیرناهنجار دسته‌بندی می‌کنیم. (y = 0 برای نمونه هنجار و y = 1 برای نمونه ناهنجار).
به جای هنجار بگیم طبیعی یا عادی
برای ترجمه normal

2020-10-30 14:02 UTC, faribajpr commented on content/week9/problem-motivation.md
> +یک "مدل" $p(x)$ تعریف می‌کنیم که احتمال ناهنجار بودن نمونه را مشخص خواهد کرد. همچنین از یک آستانه $\epsilon$(اپسیلون) به عنوان یک خط جداکننده استفاده می‌کنیم که تعیین می‌کند کدام  نمونه‌ها ناهنجار هس
اره فعل رو اشتباه نوشتم اما به جای می‌گوید فک کنم همون بگیم مشخص خواهد کرد بهتره.

2020-10-30 14:04 UTC, faribajpr commented on content/week9/gaussian-distribution.md
> +علامت $\sim$ یا 'tilde' "توزیع شده به طوریکه" نیز خوانده می‌شود.
اره به صورت هم خوبه! یه جوری بود کلا

2020-10-30 14:08 UTC, faribajpr commented on content/week9/algorithm.md
> +این مسئله در آمار "فرض مستقل" بر روی مقدار ویژگی‌ها در یک نمونه آموزشی x نامیده می‌شود.
مقادیر ویژگی ها یه جوریه به نظرم! 
بگیم فرض استقلال بر روی مقدار ویژگی های یک نمونه اموزشی x

2020-10-30 14:11 UTC, faribajpr commented on content/week9/developing-evaluating-anomaly-detection-system.md
> +برای ارزیابی الگوریتم یادگیری، داده‌های دارای برچسب را به نمونه‌های ناهنجار و غیرناهنجار دسته‌بندی می‌کنیم. (y = 0 برای نمونه هنجار و y = 1 برای نمونه ناهنجار).
اره خوبه

2020-11-02 08:50 UTC, mehrdad-dev requested changes

2020-11-02 08:50 UTC, mehrdad-dev commented on content/week9/choosing-what-features-to-use.md
> +می‌توان هرکدام از موارد بالا را برای دستیابی به شکل گاوسی در داده‌ها امتحان کرد.
ما می‌توانیم با هر یک از اینها بازی کنیم تا شکل داده های گوسی را بدست آوریم.
We can play with each of these to try and achieve the gaussian shape in our data.

2020-11-02 08:50 UTC, mehrdad-dev commented on content/week9/choosing-what-features-to-use.md
> +یک **روند تحیل خطا** برای تشخیص ناهنجاری وجود دارد که بسیار شبیه روندی است که در یادگیری با نظارت به کار برده می‌شود.
error analysis  و تجزیه و تحلیل معنی میکنن
به خاطر همین فک کنم اگه بگیم روش تجزیه و تحلیل خطا بهتر باشه

2020-11-02 08:50 UTC, mehrdad-dev commented on content/week9/multivariate-gaussian-distribution.md
> +title: "توزیع چند متغیره گاوسی(اختیاری)"
توزیع گاوسی چند متغیره
توی کل فایل

2020-11-02 08:50 UTC, mehrdad-dev commented on content/week9/multivariate-gaussian-distribution.md
> +توزیع چند متغیره گاوسی در واقع گسترش تشخیص ناهنجاری است و ممکن است (یا ممکن نیست) ناهنجاری‌های بیشتری را پیدا کند.
در واقع تعمیم تشخیص ناهنجاری است

2020-11-02 08:50 UTC, mehrdad-dev commented on content/week9/multivariate-gaussian-distribution.md
> +تغییر دادن $\Sigma$ شکل، پهنا و جهت خطوط را تغییر می‌دهد. تغییر $\mu$ مرکز توزیع را جابجا خواهد کرد.
متغیر سیگما شکل، پهنا و  ...

Varying = متغیر

2020-11-02 08:50 UTC, mehrdad-dev commented on content/week9/multivariate-gaussian-distribution.md
> +- توزیع چندمتغیره گاوسی http://cs229.stanford.edu/section/gaussians.pdf Chuong B. Do, October 10, 2008.
[توزیع چندمتغیره گاوسی](http://cs229.stanford.edu/section/gaussians.pdf) Chuong B. Do, October 10, 2008.

2020-11-03 09:59 UTC, faribajpr commented on content/week9/choosing-what-features-to-use.md
> +می‌توان هرکدام از موارد بالا را برای دستیابی به شکل گاوسی در داده‌ها امتحان کرد.
ببین درسته که از اون کلمه استفاده کرده اما توی ترجمه جالب نمیشه بگیم با هریک از اینها بازی کنیم!

2020-11-03 10:10 UTC, faribajpr commented on content/week9/anomaly-detection-vs-supervised-learning.md
> +- هنگامی که انواع مختلفی از ناهنجاری‌ها داریم و یادگیری ناهنجاری‌ها از بین نمونه‌های مثبت برای الگوریتم سخت خواهد بود. ناهنجاری‌های آینده ممکن است شبیه هیچ یک از ناهنجاری‌هایی که تا کنون دیده‌ایم نبا
و یادگیری از نمونه های مثبت و در نتیجه  تشخیص ناهنجاری ها برای الگوریتم سخت خواهد بود.

این چطوره؟

2020-11-03 20:12 UTC, mehrdad-dev commented on content/week9/anomaly-detection-vs-supervised-learning.md
> +- هنگامی که انواع مختلفی از ناهنجاری‌ها داریم و یادگیری ناهنجاری‌ها از بین نمونه‌های مثبت برای الگوریتم سخت خواهد بود. ناهنجاری‌های آینده ممکن است شبیه هیچ یک از ناهنجاری‌هایی که تا کنون دیده‌ایم نبا
نه کلن معنی اصلی رو داغون میکنه
اون دقیقا منظورش هر الگوریتمیه
به نظرم همون بهتره

2020-11-03 20:26 UTC, mehrdad-dev commented on content/week9/choosing-what-features-to-use.md
> +می‌توان هرکدام از موارد بالا را برای دستیابی به شکل گاوسی در داده‌ها امتحان کرد.
ما می‌توانیم هر یک از این ها را دست کاری کنیم ...

2020-11-04 18:21 UTC, mehrdad-dev approved these changes

2020-11-04 18:22 UTC, merged