week9-final parts
mehrdad-dev/ml-andrew-ng-code pull request #14
Opened 2020-11-06 12:38 UTC by faribajpr

2020-11-11 06:37 UTC, mehrdad-dev requested changes
Thanks

2020-11-11 11:46 UTC, faribajpr commented on content/week9/problem-formulation.md
> +یکی از معروف‌‌ترین کاربردهای یادگیری ماشین، سیستم پیشنهاد است.
اره بهتره

2020-11-11 11:55 UTC, faribajpr commented on content/week9/collaborative-filtering-algorithm.md
> +title: "الگوریتم فیلترینگ مشارکتی"
من اینو تو سایت ها هم دیدم! تازه معنی مشترک و مشارکتی یکم فرق داره به نظرم

2020-11-11 11:57 UTC, faribajpr commented on content/week9/collaborative-filtering-algorithm.md
> +<br/><br/>
اره چون فرموله یکم طولانیه و بعد یکم شلوغ میشد. اینو گذاشتم که یکم فاصله بندازه که راحتتر باشه خوندن

2020-11-11 11:57 UTC, faribajpr commented on content/week9/vectorization.md
> +title: "بردارسازی: فاکتورسازی ماتریس پایین رتبه"
اره درجه پایین هم درست تره

2020-11-11 12:23 UTC, mehrdad-dev commented on content/week9/collaborative-filtering-algorithm.md
> +<br/><br/>
اینجور موقع ها دو تا $$ بزار
مثلا اینجوری
$$
x_j
$$

2020-11-11 12:26 UTC, mehrdad-dev commented on content/week9/collaborative-filtering-algorithm.md
> +title: "الگوریتم فیلترینگ مشارکتی"
همون فیلترینگ مشارکتی بهتره

2020-11-12 07:13 UTC, mehrdad-dev approved these changes
Thanks!

2020-11-12 07:13 UTC, merged