added week7 kernels1
mehrdad-dev/ml-andrew-ng-code pull request #15
Opened 2020-11-06 12:58 UTC by nargesrzn

2020-11-08 08:29 UTC, mehrdad-dev requested changes

2020-11-08 08:29 UTC, mehrdad-dev commented on content/week7/kernels1.md
> +$\sigma^2$ یک پارامتر هسته گوسی است و می توان آن را تغییر داد تا افت ویژگی $f_i$ ما را کم یا زیاد کند. همراه با نگاه کردن
کرنل گواسی
نظرت چیه همون drop-off خودشو بزاریم فعلا

2020-11-08 09:39 UTC, nargesrzn commented on content/week7/kernels1.md
> +$\sigma^2$ یک پارامتر هسته گوسی است و می توان آن را تغییر داد تا افت ویژگی $f_i$ ما را کم یا زیاد کند. همراه با نگاه کردن
منظورت اینه که همون حالت انگلیسی بذارم؟

2020-11-09 06:49 UTC, mehrdad-dev commented on content/week7/kernels1.md
> +$\sigma^2$ یک پارامتر هسته گوسی است و می توان آن را تغییر داد تا افت ویژگی $f_i$ ما را کم یا زیاد کند. همراه با نگاه کردن
اره

2020-11-11 06:39 UTC, mehrdad-dev approved these changes
Thanks

2020-11-11 06:39 UTC, merged