modified model-selection, added regularization and bias/variance, dia…
mehrdad-dev/ml-andrew-ng-code pull request #8
Opened 2020-10-16 21:35 UTC by faribajpr

…gnosing bias/variance, learning curves. in regularization and bias/variance, in line 29 the formula doesn't work. and 4 images added

2020-10-17 09:44 UTC, mehrdad-dev requested changes
Thanks!
Great work.

Please see comments in review and fix them.
And if you have opinion or better changes please write this as a comment.

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/diagnosing-bias-variance.md
> +مادامی که ما درجه چندجمله ای(d) را افزایش می دهیم، خطای آموزشی کاهش می یابد.
training error:
خطای آموزش or خطای آموزشی

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/regularization-and-bias-variance.md
> +- مقدار کم $\lambda$: واریانس بالا (overfitting)
به نظرم کلمه **مقدار** رو حذف کنیم
بعلاوه به جای مقدار زیاد بنویسیم :
$\lambda$ بزرگ
$\lambda$ متوسط
$\lambda$ کوچک

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/regularization-and-bias-variance.md
> +مقدار بالای $\lambda$ باعث خسارت دیدن تمام مقادیر $\Theta$ که خط تابع حاصل شده را به شدت ساده کرده و در نهایت موجب underfitting خواهد شد.
مقدار بالای $\lambda$ :

$\lambda$ بزرگ

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/regularization-and-bias-variance.md
> +رابطه $\lambda$ با مجموعه آموزشی و مجموعه cross validation به صورت زیر است:
`to the training set and the variance set is as follows`

به جای مجموعه cross validation باید از مجموعه واریانس استفاده کرد
طبق جمله بالا

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/regularization-and-bias-variance.md
> +برای انتخاب مدل و مقدار $\lambda$ در منظم سازی، باید:
باید: -> نیاز داریم که:

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/regularization-and-bias-variance.md
> +4. خطای cross validation را به کمک $\Theta$ محاسبه شده با $\lambda$ روی $J_{cv}\left ( \Theta  \right )$، و بدون منظم سازی($\lambda = 0$) محاسبه کنید.
با کمک  $\Theta$ آموخته شده

بدون منظم سازی یا \lambda = 0

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/regularization-and-bias-variance.md
> +6. با استفاده از بهترین ترکیب $\Theta$ و $\lambda$، این ترکیب را روی $J_{test}\left ( \Theta  \right )$ پیاده کرده تا از اینکه منظم سازی مناسبی برای مسئله دارد اطمینان حاصل کنید.
تا اطمینان حاصل کنید از اینکه آیا تعمیم خوبی در مورد مسئله وجود دارد یا خیر

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/learning-curves.md
> +- همچنان که مجموعه آموزشی بزرگتر می شود، خطای تابع درجه دو افزایش می یابد.
هرچه مجموعه آموزشی بزرگ تر می‌شود

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/learning-curves.md
> +- مقدار خطا پس از اندازه معین m یا مجموعه اموزشی کم و ثابت خواهد بود.
اموزشی -> آموزشی

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/learning-curves.md
> +**مقدار واریانس بالا**
**با واریانس زیاد:**

لطفا یک خط اضافه بعد از این خط هم ایجاد بشه

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/learning-curves.md
> +**مقدار بایاس بالا**
**با بایاس زیاد:**

2020-10-17 09:44 UTC, mehrdad-dev commented on content/week6/learning-curves.md
> +**مجموعه آموزشی کوچک:** $J_{train}\left ( \Theta  \right )$ مقدار کم و $J_{CV}\left ( \Theta  \right )$ مقدار بالایی داشته باشد.
مقداری کم
و مقدار زیادی داشته باشد

2020-10-17 14:26 UTC, faribajpr commented on content/week6/model-selection.md
> +1. برای هر درجه چندجمله ای، با استفاده از مجموعه آموزشی، پارامتر $\Theta$ را  بهینه سازی کنید.
به جای پارامترهای داخل تتا، میشه هم بگیم پارامترهای موجود در تتا، یا فقط پارامترهای تتا. داخل تتا جالب نیست به نظرم

2020-10-17 14:33 UTC, mehrdad-dev commented on content/week6/model-selection.md
> +1. برای هر درجه چندجمله ای، با استفاده از مجموعه آموزشی، پارامتر $\Theta$ را  بهینه سازی کنید.
موافقم
پارامتر های موجود در تتا خوبه

2020-10-17 14:53 UTC, faribajpr commented on content/week6/diagnosing-bias-variance.md
> +title: "تشخیص بایاس و واریانس"
yes, it's better

2020-10-17 14:58 UTC, faribajpr commented on content/week6/diagnosing-bias-variance.md
> +date: 2020-10-16T19:43:49.155Z
sorry, should I create the file again?

2020-10-17 15:18 UTC, faribajpr commented on content/week6/diagnosing-bias-variance.md
> +- بایاس بالا همان underfitting و واریانس بالا همان overfitting است که باید یک میانگین مناسب بین این دو مقدار انتخاب شود.
زیاد مطمئن نیستم. اما عوضش می‌کنم

2020-10-17 15:20 UTC, faribajpr commented on content/week6/diagnosing-bias-variance.md
> +مادامی که ما درجه چندجمله ای(d) را افزایش می دهیم، خطای آموزشی کاهش می یابد.
خطای آموزش :)

2020-10-17 15:28 UTC, faribajpr commented on content/week6/regularization-and-bias-variance.md
> +رابطه $\lambda$ با مجموعه آموزشی و مجموعه cross validation به صورت زیر است:
oh, right, it was my mistake

2020-10-17 16:21 UTC, faribajpr commented on content/week6/regularization-and-bias-variance.md
> +6. با استفاده از بهترین ترکیب $\Theta$ و $\lambda$، این ترکیب را روی $J_{test}\left ( \Theta  \right )$ پیاده کرده تا از اینکه منظم سازی مناسبی برای مسئله دارد اطمینان حاصل کنید.
تعمیم خوبی => تعمیم مناسبی

isn't it better?

2020-10-18 06:13 UTC, mehrdad-dev commented on content/week6/diagnosing-bias-variance.md
> +date: 2020-10-16T19:43:49.155Z
نه این سری مشکلی نداره حالا

2020-10-18 06:13 UTC, mehrdad-dev commented on content/week6/model-selection.md
> +1. برای هر درجه چندجمله ای، با استفاده از مجموعه آموزشی، پارامتر $\Theta$ را  بهینه سازی کنید.
آره بد نیست
ولی خوب چون مستقیم از کلمه bad استفاده کرده اونطوری نوشتم
this is a bad method

2020-10-18 08:34 UTC, mehrdad-dev requested changes
thanks please check new comments ❤️

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +- یک شبکه عصبی با تعداد بیشتری از پارامتر مستعد overfitting خواهد بود و **محاسبات سنگینی** خواهد داشت. در این شرایط می‌توانید از منظم‌سازی (افزایش $\lambda$) برای اصلاح overfitting استفاده کنید.
همچنین از نظر محاسباتی گران است

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +استفاده از یک لایه پنهان واحد پیش‌ فرض مناسبی برای شروع است. با کمک مجموعه cross validation می‌توان شبکه عصبی را روی تعدادی از لایه‌های پنهان آموزش داد.
`استفاده از یک لایه پنهان واحد`
اگر بگیم استفاده از یک عدد لایه پنهان بهتر نیست؟

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +انتخاب ترتیب چندجمله‌ای‌ها(M).\
\

انتخاب M به ترتیب چند جمله ای ها

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +راه‌های گوناگونی برای حل این مشکل وجود دارد:
فک کنم اینجا مسئله بیشتر بهش بخوره تا مشکل

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +- انتخاب مدلی که بیشترین سازگاری را با دیتا دارد و باعث overfitting نخواهد شد (این روش هم بسیار مشکل است).
داده
https://mehrdad-dev.github.io/ml-andrew-ng/dictionary

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +**بایاس: خطای تخمینی (اختلاف مقدار مورد نظر و مقدار بهینه)**
approximation error
اینو اگه **خطای تقریب** بزاریمش بهتر نیست؟
چون یک جای دیگه هم تقریب ترجمه کردیم
باید به دیکشنری هم اضافه اش کنیم

 estimation error میشه خطای تخمین

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +- $J_{train }\left ( \Theta  \right )$ و $J_{CV }\left ( \Theta  \right )$ مقادیر بالایی خواهند داشت و $J_{train }\left ( \Theta  \right ) \approx J_{CV}\left ( \Theta  \right )$
مقادیر زیادی؟

2020-10-18 08:34 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +یکی از مهم‌ترین اهداف در یادگیری: پیدا کردن صحیح‌ترین مدل در متوازن کردن بایاس و واریانس
فک کنم بهتر باشه بگیم:
پیدا کردن مدلی که در بایاس و واریانس متوازن باشد

2020-10-18 13:44 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +روند تصمیم‌گیری ما می‌تواند به مراحل زیر تقسیم‌بندی شود:
اره این خیلی بهتره! من تا جایی که میتونستم هم برای بایاس و واریانس از زیاد و کم استفاده کردم

2020-10-18 13:46 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +- جمع‌آوری نمونه آموزش بیشتر\
آره درستش کردم، بی دقتی بود :))

2020-10-18 13:53 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +- یک شبکه عصبی با تعداد پارامترهای کم مستعد underfitting خواهد بود. همچنین این شبکه عصبی **محاسبات ارزانی** خواهد داشت.
واسه جفتشون بگم که از نظر محاسباتی هزینه کم و زیادی دارند؟

2020-10-18 13:55 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +استفاده از یک لایه پنهان واحد پیش‌ فرض مناسبی برای شروع است. با کمک مجموعه cross validation می‌توان شبکه عصبی را روی تعدادی از لایه‌های پنهان آموزش داد.
فک کنم "یک لایه پنهان" خالی هم خوب باشه نه؟

2020-10-18 13:57 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +انتخاب ترتیب چندجمله‌ای‌ها(M).\
اره این خیلی خوبه

2020-10-18 13:59 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +**بایاس: خطای تخمینی (اختلاف مقدار مورد نظر و مقدار بهینه)**
اها اره مینویسم خطای تخمین

2020-10-18 14:01 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +یکی از مهم‌ترین اهداف در یادگیری: پیدا کردن صحیح‌ترین مدل در متوازن کردن بایاس و واریانس
اره اره!!

2020-10-18 14:02 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +یکی از مهم‌ترین اهداف در یادگیری: پیدا کردن صحیح‌ترین مدل در متوازن کردن بایاس و واریانس
پیدا کردن مدلی که با بایاس و واریانس در توازن باشد هم میشه!

2020-10-18 14:09 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +- یک شبکه عصبی با تعداد پارامترهای کم مستعد underfitting خواهد بود. همچنین این شبکه عصبی **محاسبات ارزانی** خواهد داشت.
ارزان فک کنم درست تر باشه حالا
اون پایینی رو توی یک کامنت دیگه گفتم
نمیدونم نظر خودت چیه

2020-10-18 14:10 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +استفاده از یک لایه پنهان واحد پیش‌ فرض مناسبی برای شروع است. با کمک مجموعه cross validation می‌توان شبکه عصبی را روی تعدادی از لایه‌های پنهان آموزش داد.
نه خالی اصن یک معنی دیگه میده
یعنی اون لایه پنهانه هیچ گره ای نداره مثلا

2020-10-18 14:11 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +**بایاس: خطای تخمینی (اختلاف مقدار مورد نظر و مقدار بهینه)**
نه فک کنم اشتباه متوجه شدی
approximation error این میشه خطای تقریب

2020-10-18 14:11 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +یکی از مهم‌ترین اهداف در یادگیری: پیدا کردن صحیح‌ترین مدل در متوازن کردن بایاس و واریانس
اره این خوبه

2020-10-18 14:12 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +استفاده از یک لایه پنهان واحد پیش‌ فرض مناسبی برای شروع است. با کمک مجموعه cross validation می‌توان شبکه عصبی را روی تعدادی از لایه‌های پنهان آموزش داد.
خب پس همون یک عدد لایه پنهان باشه

2020-10-18 14:15 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +- یک شبکه عصبی با تعداد بیشتری از پارامتر مستعد overfitting خواهد بود و **محاسبات سنگینی** خواهد داشت. در این شرایط می‌توانید از منظم‌سازی (افزایش $\lambda$) برای اصلاح overfitting استفاده کنید.
توی ذهن که ادم ترجمه میکنه همون ارزان و گران درسته! اما توی متن نمیدونم! :))

2020-10-18 14:15 UTC, mehrdad-dev commented on content/week6/deciding-what-to-do-next.md
> +روند تصمیم‌گیری ما می‌تواند به مراحل زیر تقسیم‌بندی شود:
اره یک جا دیگه به چشمم خورد کامنتشو نبستم هنوز
از بالا نگاه کنی پیدا میشه
اگرم نباشه حتما درستش کردی تا الان

2020-10-18 16:58 UTC, faribajpr commented on content/week6/deciding-what-to-do-next.md
> +**بایاس: خطای تخمینی (اختلاف مقدار مورد نظر و مقدار بهینه)**
اها اره!! ببخشید! درستش کردم

2020-10-19 07:24 UTC, merged

2020-10-19 07:50 UTC, mehrdad-dev reviewed
finish