added trading-off-precision-and-recal, prioritizing-what-to-work-on, …
mehrdad-dev/ml-andrew-ng-code pull request #9
Opened 2020-10-19 19:44 UTC by faribajpr

…error-metrics-for-skewed-classes, error-analysis & data-for-machine-learning

2020-10-20 17:47 UTC, mehrdad-dev requested changes
Thanks @faribajpr

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +ممکن است ما نیاز به یک پیش بینی مطمئن از دو کلاس، به وسیله رگرسیون لجستیک داشته باشیم. یک راه افزایش آستانه است:
به نظرم بعد از دو کلاس ویرگول نزاریم بهتره

یک راه این است که آستانه خود را افزایش دهیم:

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +بدین صورت تنها درصورتی که بیمار 70% شانس بیماری داشته باشد، سرطان را پیش بینی می‌کنیم.
بدین ترتیب بگیم شاید جالب تر باشه
چون دو بار صورت آوردیم پشت هم

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +در یک مثال معکوس، میتوان آستانه را کمتر کرد:
در یک مثال متفاوت بگیم یکم عمومی تره
مثال معکوس یکجوریه

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +راه حل بهتر محاسبه امتیاز F خواهد بود(یا امتیاز F1):
امتیاز F :/
خیلی داغون نظرت چیه
خودش یا همین یا یک معنی دیگه

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +مقدار precision و recall را روی **مجموعه cross validaion**  آموزش می‌دهیم تا باعث انحراف مجموعه آزمون نشود.
ما می‌خواهیم precision و recall روی مجموعه cross validaion آموزش دهیم،
تا مجموعه آزمون ما دچار بایاس نشود.

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/data-for-machine-learning.md
> +title: "داده لازم برای یادگیری ماشین"
کلمه لازم نداره داخلش
داده برای یادگیری ماشین

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/data-for-machine-learning.md
> +ما باید به ویژگی‌هایی با اطلاعات کافی انتخاب کنیم. یک آزمون مفید به این صورت است که: با توجه به ورودی x، آیا یک متخصص انسانی می‌تواند با اطمینان y را پیش بینی کند؟
ما باید ویژگی های خود را انتخاب کنیم تا اطلاعات کافی داشته باشیم.
یا
ما باید به ویژگی‌هایی با اطلاعات کافی انتخاب کنیم

2020-10-20 17:47 UTC, mehrdad-dev commented on content/week6/data-for-machine-learning.md
> +**منطق داده‌های بزرگ**: اگر یک الگوریتم با بایاس پایین داشته باشیم(ویژگی‌های زیاد یا واحدهای پنهان یک تابع بسیار پیچیده می‌سازد)، پس هرچه مجموعه آموزشی بزرگتر باشد، overfitting کمتری خواهیم داشت(و ال
بایاس کم

2020-10-21 06:41 UTC, mehrdad-dev requested changes
Thanks

2020-10-21 12:55 UTC, faribajpr commented on content/week6/error-metrics-for-skewed-classes.md
> +title: "استانداردهای خطا برای کلاس‌های نامتوازن"
من میگم بنویسیم معیار خطا برای کلاس های نامتوازن! چون معنی نامتوازن هم درسته، طبق تعرفش هم این معنی بهش میاد

2020-10-21 12:57 UTC, faribajpr commented on content/week6/error-metrics-for-skewed-classes.md
> +این مسئله در کلاس‌های نامتوازن رخ می‌دهد، هنگامی که کلاس در کل مجموعه داده بسیار نادر باشد.
جفتش به نظرم دسته! هرکدومو میگی بذارم

2020-10-21 12:58 UTC, faribajpr commented on content/week6/error-metrics-for-skewed-classes.md
> +#### $\frac{\text{True Positives}}{\text{Total number of predicted positives}} = \frac{\text{True Positives}}{\text{True Positives + False positives}}$
گفتم یکم بزرگ باشن! تگشونو برمیدارم فقط نمیدونم چجوری Center میشن بعدش

2020-10-21 13:01 UTC, faribajpr commented on content/week6/error-metrics-for-skewed-classes.md
> +این دو مقیاس دید بهتری نسبت به این که عملکرد طبقه‌بندی ما چگونه است.
آره الان دیدم!! حواسم به اون جمله دوم نبوده اصن

2020-10-21 13:02 UTC, faribajpr commented on content/week6/trading-off-precision-and-recall.md
> +ممکن است ما نیاز به یک پیش بینی مطمئن از دو کلاس، به وسیله رگرسیون لجستیک داشته باشیم. یک راه افزایش آستانه است:
فقط مینویسم استانه را افزاش دهیم، نه استانه خود

2020-10-21 13:08 UTC, faribajpr commented on content/week6/trading-off-precision-and-recall.md
> +در یک مثال معکوس، میتوان آستانه را کمتر کرد:
آره الان نگاه میکنم یطوریه! ولی تو متن منظورش یه مثالی هست که کاملا برعکسه! بنویسم متفاوت اوکیه؟

2020-10-21 13:09 UTC, faribajpr commented on content/week6/trading-off-precision-and-recall.md
> +راه حل بهتر محاسبه امتیاز F خواهد بود(یا امتیاز F1):
اره نظر خودمم داغونه! اگه موافقی اصل کلمه رو بذاریم به انگلیسی

2020-10-21 13:20 UTC, faribajpr commented on content/week6/data-for-machine-learning.md
> +ما باید به ویژگی‌هایی با اطلاعات کافی انتخاب کنیم. یک آزمون مفید به این صورت است که: با توجه به ورودی x، آیا یک متخصص انسانی می‌تواند با اطمینان y را پیش بینی کند؟
اون "به" از دستم در رفته! میشه:
ما باید ویژگی هایی با اطلاعات کافی انتخاب کنیم

2020-10-21 16:52 UTC, mehrdad-dev commented on content/week6/error-metrics-for-skewed-classes.md
> +title: "استانداردهای خطا برای کلاس‌های نامتوازن"
خوبه

2020-10-21 16:53 UTC, mehrdad-dev commented on content/week6/error-metrics-for-skewed-classes.md
> +این مسئله در کلاس‌های نامتوازن رخ می‌دهد، هنگامی که کلاس در کل مجموعه داده بسیار نادر باشد.
بسیار نادر است :)))))

2020-10-21 16:54 UTC, mehrdad-dev commented on content/week6/error-metrics-for-skewed-classes.md
> +#### $\frac{\text{True Positives}}{\text{Total number of predicted positives}} = \frac{\text{True Positives}}{\text{True Positives + False positives}}$
باید به جای یکدونه $ اول و آخر لاتکس
دو تا بزاری یعنی:
$$
blah blah blah
$$
اینجوری

2020-10-21 16:56 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +ممکن است ما نیاز به یک پیش بینی مطمئن از دو کلاس، به وسیله رگرسیون لجستیک داشته باشیم. یک راه افزایش آستانه است:
اینم میشه
چون خودش توی جمله نوشته بود اینطوری گفتم

2020-10-21 16:57 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +در یک مثال معکوس، میتوان آستانه را کمتر کرد:
میدونم ولی وقتی به فارسی برمیگردونیش مث قبل معنی نمیده زیاد
اره متفاوت بهتره

2020-10-21 16:58 UTC, mehrdad-dev commented on content/week6/trading-off-precision-and-recall.md
> +راه حل بهتر محاسبه امتیاز F خواهد بود(یا امتیاز F1):
اره خودشو بزاریم

2020-10-21 17:00 UTC, mehrdad-dev commented on content/week6/data-for-machine-learning.md
> +ما باید به ویژگی‌هایی با اطلاعات کافی انتخاب کنیم. یک آزمون مفید به این صورت است که: با توجه به ورودی x، آیا یک متخصص انسانی می‌تواند با اطمینان y را پیش بینی کند؟
نه منظورم بیشتر روی معنی که دو جمله میدن بود
چون منظورش تغییر میکنه اگه بالایی باشه

2020-10-22 18:34 UTC, faribajpr commented on content/week6/data-for-machine-learning.md
> +ما باید به ویژگی‌هایی با اطلاعات کافی انتخاب کنیم. یک آزمون مفید به این صورت است که: با توجه به ورودی x، آیا یک متخصص انسانی می‌تواند با اطمینان y را پیش بینی کند؟
اره!! معنی جمله اول درسته! بنویسم ما باید ویژگی هایی را انتخاب کنیم تا اطلاعات کافی داشته باشیم خوبه؟

2020-10-23 06:28 UTC, mehrdad-dev reviewed
👍

2020-10-23 06:28 UTC, merged